"""
Django settings for dwebsite project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '16=iig$bzcgfqf^kh%8j2%ik7(0qys^o4=q8jninw&uu-8*fg+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'blog'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dwebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dwebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/upload/'
MEDIA_ROOT = os.path.join(BASE_DIR,'upload').replace('\\','/')


CORS_ALLOW_CREDENTIALS = True 
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ( 
    'http://127.0.0.1',
    'http://8.131.225.131:81',
    'https://www.wangblog.club'
)

CORS_ALLOW_METHODS = ( 
    'DELETE', 
    'GET', 
    'OPTIONS', 
    'PATCH', 
    'POST', 
    'PUT', 
    'VIEW', 
)

CORS_ALLOW_HEADERS = ( 
    'XMLHttpRequest', 
    'X_FILENAME', 
    'accept-encoding', 
    'authorization', 
    'content-type', 
    'dnt', 
    'origin', 
    'user-agent', 
    'x-csrftoken', 
    'x-requested-with', 
    'Pragma', 
)


ALIPAY_APPID = "2021002115679744"

ALIPAY_URL = "https://openapi.alipay.com/gateway.do"

ALIPAY_NOTIFY_URL = "https://www.wangblog.club/pay_result/"

ALITAY_RETURN_URL = "https://www.wangblog.club/"

APP_PRIVATE_KEY = 'MIIEowIBAAKCAQEAp03wNgdeHudS/C0qoo6FSMm6xL2dBQgjSYdw4MUnZMjDjtZii7AfrbBEDe5/ANHCKUGjnWSSo2rzzhGkr6mjWOboA2zgk6Xo1T4lyK59tRPwGcEEBuQdfjJwLLpgdhJwh6ub1jA5huFXhR4KRvHLvTgBzwXRizFe4S6XqR3icWYRkBCV2S1Td//VmkCAjDu/nSR/xbzrc7QdvoN/HvnG0S0mpvcNauDZwZ4zxMCXX3d7QTosI+Zcg6RqENVFWpDfoanKK1WJ15WjgiOSjdPZfwkt/prliJOeTYvgMDg4T2wuFoOt9nFcbvUHImCHP374S6q6smWAbBvjIWgIhr6YeQIDAQABAoIBAQCkrh3dQMFPkAlqOhc2bS0a6Z6S28V8V3dMgCoGxWmyVb/QkIvtzc5QzCkgwXp31wDUVUz0tzNz8enMFCfT1Rn5f0gvXvNrwip+BC9y6vbHz7lN0GTjV5UETCeIj2g1sI7drHi3iz6E2rioSlp5XLZcKY32Nlb9OPqYkqEsEUN8tBDX1MGkbdEeqQGvY+52MyXbR75xDnNnqUswnNd5HXeMnCZceo+MeQXJ2b4neWSwZx03HZnUy+9Y4PB5oj1c9CE86z4qiPeTQfchusK+BqwOcfy6TxXHidkD16ExFFxt6c5CTvciJVjHc/ggzrfOudTX1y5XBGndOPOB+hRzZ/UVAoGBANQgGoI6tlWnn0E8mcGaQyAcLGpJHq5JQSrUCfYLRbyH4K64bvlE4fusnSQ3ljsz+OZc766QEk0XaP7+nvBpc1jpnAt6z/rFBajHZ4hfNnul92hhr3rRiacHILOBRzUeE0S1RqfkoIHKzF8wjT1gD3ECgfetcLulAxml5jo5qtpjAoGBAMnomG1zqdMx7Ml+Y3Yq4EzfCuEq7aEyoxk6Q5iaBvhQHiALUqjRYdnqaq5DqO3DyLizuNRHQBWkXlXLSBATp5hsBkGPxASHirpFc6RE+7AoJvyMAL0qLkFNtcfzHfYBKmKOP10Df/EeiNg+0VBV6zXk98xpcB6/ZRLKrNFtIOpzAoGAToG/LdmK5/KMlzlVcnikRTsIGSIMr9Y+vxoQwbX0Tk0/k4qAz9J1jI6a7e+As1KN2LwmnMWHcG6slksoCbQNU6fJ79m5JYdLi+aY47jRUjvfcAtPRbZNKrsRmD3NW9RQr0oj5zlPShoDP2uZqlBmBp41+bOAGIJ+vjxPE9eJ6x8CgYBYfzdYOesEo4xKoLgNkitv5g8JtFwlXGF6bDw2hcRqUAt0NiJL1kJSVlnd+c/wLvEqa7Omb3haRAoJBqmWSlcaCrcPQ2lCJvqaPFi8dnPuuRqldOPaBcPyYZI8ioXmTop6WijRpvgMAjsutRHfaVlH7Qzjro8zGua9PtJSlMdpmwKBgDBcxJJIho/fPIa7jfpLWOKdgtz+aGl4KLIcOmeQdCFjIeSSKo5ydVyTVqOc1qtWwp3NKj+k3qr+VRzg16MD2dNdjKxMV7AqWPKGAUNMbu3iOMAOVs4YH9EGnF+bTpNAgPNQJ0+REdAazAKrgOKSLlkPJzp5o8I0dI8BB+S5AjSG'

ALIPAY_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp03wNgdeHudS/C0qoo6FSMm6xL2dBQgjSYdw4MUnZMjDjtZii7AfrbBEDe5/ANHCKUGjnWSSo2rzzhGkr6mjWOboA2zgk6Xo1T4lyK59tRPwGcEEBuQdfjJwLLpgdhJwh6ub1jA5huFXhR4KRvHLvTgBzwXRizFe4S6XqR3icWYRkBCV2S1Td//VmkCAjDu/nSR/xbzrc7QdvoN/HvnG0S0mpvcNauDZwZ4zxMCXX3d7QTosI+Zcg6RqENVFWpDfoanKK1WJ15WjgiOSjdPZfwkt/prliJOeTYvgMDg4T2wuFoOt9nFcbvUHImCHP374S6q6smWAbBvjIWgIhr6YeQIDAQAB'
